[Autologin]
Relogin=false
Session=openbox
User=liveuser

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=archcraft
CursorTheme=Qogirr
#CursorSize=16
Font=Iosevka,10,-1,0,50,0,0,0,0,0
