[General]
DisplayServer=x11
Numlock=off
InputMethod=qtvirtualkeyboard
Namespaces=

[Theme]
ThemeDir=/usr/share/sddm/themes
FacesDir=/usr/share/sddm/faces
EnableAvatars=true

[Users]
DefaultPath=/usr/local/sbin:/usr/local/bin:/usr/bin:/bin
MinimumUid=1000
MaximumUid=60513
HideUsers=
HideShells=
RememberLastSession=true
RememberLastUser=true
ReuseSession=true

[Wayland]
#CompositorCommand=
SessionDir=/usr/local/share/wayland-sessions,/usr/share/wayland-sessions
SessionCommand=/usr/share/sddm/scripts/wayland-session
SessionLogFile=.local/share/sddm/wayland-session.log
EnableHiDPI=true

[X11]
ServerPath=/usr/bin/X
ServerArguments=-nolisten tcp
XephyrPath=/usr/bin/Xephyr
SessionDir=/usr/share/xsessions
SessionCommand=/usr/share/sddm/scripts/Xsession
SessionLogFile=.local/share/sddm/xorg-session.log
DisplayCommand=/usr/share/sddm/scripts/Xsetup
DisplayStopCommand=/usr/share/sddm/scripts/Xstop
EnableHiDPI=true
